// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List available products in the Fresh store (vegetables, fruits, meat, fish, poultry).",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter."),
    only_available: z.boolean().optional().describe("Return only in-stock/available products.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, only_available }) => {
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let q = sb.from("products").select("id,name,category,price_iqd,unit,is_available,stock_qty,emoji").order("sort_order");
    if (category) q = q.eq("category", category);
    if (only_available) q = q.eq("is_available", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List categories",
  description: "List active product categories in the Fresh store.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await sb.from("categories").select("id,name,sort_order,is_active").eq("is_active", true).order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-delivery-zones.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_delivery_zones_default = defineTool3({
  name: "list_delivery_zones",
  title: "List delivery zones",
  description: "List active delivery zones in Kirkuk with their delivery fees in IQD.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await sb.from("delivery_zones").select("id,name,price_iqd,is_active,sort_order").eq("is_active", true).order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { zones: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-loyalty-card.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_loyalty_card_default = defineTool4({
  name: "get_loyalty_card",
  title: "Get loyalty card",
  description: "Look up a customer's public Fresh loyalty card by phone number (stamps and gifts).",
  inputSchema: {
    phone: z2.string().min(6).describe("Customer phone number as stored (e.g. 07701234567).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ phone }) => {
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await sb.from("customers").select("full_name,phone,area,total_stamps,gift_count,lifetime_orders").eq("phone", phone).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No loyalty card found for this phone." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/tools/store-status.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var store_status_default = defineTool5({
  name: "store_status",
  title: "Store status",
  description: "Check whether the Fresh store is currently open for orders.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const sb = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await sb.from("store_settings").select("is_open,closed_message,updated_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { status: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_recent_orders_default = defineTool6({
  name: "list_recent_orders",
  title: "List recent orders",
  description: "List recent Fresh orders for staff (admin/accountant/driver). Requires authentication.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max orders to return (default 20)."),
    status: z3.string().optional().describe("Optional status filter (e.g. pending, delivered).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb.from("orders").select("id,customer_name,customer_phone,customer_address,status,total_iqd,delivery_zone_name,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "loiuqxeurkzejvivlrpa";
var mcp_default = defineMcp({
  name: "fresh-kirkuk-mcp",
  title: "\u0641\u0631\u064A\u0634 Fresh - Kirkuk",
  version: "0.1.0",
  instructions: "Tools for the Fresh grocery store in Kirkuk (vegetables, fruits, meat, fish, poultry). Public tools: list_products, list_categories, list_delivery_zones, store_status, get_loyalty_card. Staff-only (requires sign-in): list_recent_orders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    list_categories_default,
    list_delivery_zones_default,
    store_status_default,
    get_loyalty_card_default,
    list_recent_orders_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
